CREATE SCHEMA `vivere_pilates` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
commit;

use VIVERE_PILATES;
COMMIT;

CREATE TABLE CAD_ALUNOS_PRINCIPAL
(
  COD int AUTO_INCREMENT,
  NOME	VARCHAR(35),
  TELEFONE	VARCHAR(30),
  DATA_NASCIMENTO	DATE,
  CPF	VARCHAR(14),
  ENDERECO	VARCHAR(200),
  EMAIL	VARCHAR(35),
  SITUACAO	VARCHAR(7),
  TELEFONE2	VARCHAR(30),
 PRIMARY KEY (COD)
);

CREATE TABLE AULA 
(
  COD INT AUTO_INCREMENT,
  CODALUNO INT NOT NULL,
  DATA_AULA	DATE,
  OBSERVACAO VARCHAR(17),
  ANOTACOES	longtext,
 PRIMARY KEY (COD)
);
ALTER TABLE AULA ADD FOREIGN KEY (CODALUNO) REFERENCES CAD_ALUNOS_PRINCIPAL (COD) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE DADOS 
(
  COD	INT auto_increment,
  CPF	VARCHAR(15),
  CREFITO	VARCHAR(20),
  NOME	VARCHAR(13),
 PRIMARY KEY (COD)
);

CREATE TABLE MENSALIDADE 
(
  CODMENSALIDADE	INT auto_increment,
  CODALUNO	INT NOT NULL,
  PAGO	VARCHAR(3),
  DATA_MENSALIDADE	DATE,
  MES	VARCHAR(9),
  ANO	VARCHAR(4),
  VALOR	DECIMAL(5, 2),
  VISUALIZAR	VARCHAR(3),
 PRIMARY KEY (CODMENSALIDADE)
);
ALTER TABLE MENSALIDADE ADD FOREIGN KEY (CODALUNO) REFERENCES CAD_ALUNOS_PRINCIPAL (COD) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE FOTO 
(
  COD	INT auto_increment,
  CODALUNO	INT,
  DATA_FOTO	DATE,
  NOMEFOTO	VARCHAR(40),
  ALUNO	VARCHAR(35),
  CAMINHO	VARCHAR(500),
 PRIMARY KEY (COD)
);
ALTER TABLE FOTO ADD FOREIGN KEY (CODALUNO) REFERENCES CAD_ALUNOS_PRINCIPAL (COD) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE AVALIACAO (
    COD INT AUTO_INCREMENT,
    CODALUNO INTEGER,
    PROFISSAO VARCHAR(30),
    INDICACAO VARCHAR(30),
    ATIVIDADEFISICA VARCHAR(3),
    QUALATIVIDADEFISICA VARCHAR(200),
    MEDICACAO VARCHAR(200),
    TABAGISMO VARCHAR(3),
    ETILISMO VARCHAR(3),
    HIPERTENSAO VARCHAR(3),
    DOENCAS VARCHAR(200),
    DORES VARCHAR(200),
    POSICAODOR VARCHAR(200),
    OBJETIVOPRINCIPAL VARCHAR(200),
    QUEIXAPRINCIPAL VARCHAR(200),
    HDA LONGTEXT,
    HPP LONGTEXT,
    PESO DECIMAL(5 , 2 ),
    ALTURA DECIMAL(5 , 2 ),
    PA VARCHAR(8),
    ENCURTAMENTOS VARCHAR(200),
    FORCAMUSCULAR VARCHAR(200),
    PES VARCHAR(200),
    JOELHOS VARCHAR(200),
    PELVE VARCHAR(200),
    COLUNA VARCHAR(200),
    OMBROS VARCHAR(200),
    ESCAPULAS VARCHAR(200),
    CABECA VARCHAR(200),
    PRIMARY KEY (COD)
);
ALTER TABLE AVALIACAO ADD FOREIGN KEY (CODALUNO) REFERENCES CAD_ALUNOS_PRINCIPAL (COD) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE EXAMES 
(
  CODEXAME	INT auto_increment,
  CODALUNO	INT,
  EXAMES	longtext,
  OBSERVACOES	longtext,
 PRIMARY KEY (CODEXAME)
);
ALTER TABLE EXAMES ADD FOREIGN KEY (CODALUNO) REFERENCES CAD_ALUNOS_PRINCIPAL (COD) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE FOTO_EXAME 
(
  COD	int auto_increment,
  CODEXAME	int,
  DATA_FOTO_EXAME	DATE,
  NOMEFOTO	VARCHAR(40),
  CAMINHO	VARCHAR(500),
  primary key (COD)
);
ALTER TABLE FOTO_EXAME ADD FOREIGN KEY (CODEXAME) REFERENCES EXAMES (CODEXAME) ON UPDATE CASCADE ON DELETE CASCADE;

commit
