INSERT INTO AULA (COD, CODALUNO, DATA_AULA, OBSERVACAO, ANOTACOES)
VALUES
(1, 1, '2014/03/24', 'COMPARECEU', 'PRIMEIRA AULA '),
(2, 4, '2013/04/25', 'COMPARECEU', 'PRIMEIRA AULA '),

(13, 171, '2019/03/08', 'COMPARECEU', 'US DICLO, ALONGAMENTO ANTERIOR MAIS CRIO '),

(3, 3, '2014/08/08', 'COMPARECEU', 'PRIMEIRA AULA '),

(4, 2, '2017/11/27', 'COMPARECEU', 'PRIMEIRA AULA '),

(5, 5, '2018/10/04', 'COMPARECEU', 'PRIMEIRA AULA '),

(6, 6, '2018/08/07', 'COMPARECEU', 'PRIMEIRA AULA '),

(7, 7, '2011/05/25', 'COMPARECEU', 'PRIMEIRA AULA '),

(8, 8, '2013/07/11', 'COMPARECEU', 'PRIMEIRA AULA '),

(9, 9, '2013/03/06', 'COMPARECEU', 'PRIMEIRA AULA '),

(10, 10, '2018/10/24', 'COMPARECEU', 'PRIMEIRA AULA '),

(11, 11, '2012/01/09', 'COMPARECEU', 'PRIMEIRA AULA '),

(12, 13, '2018/06/25', 'COMPARECEU', 'PRIMEIRA AULA '),

(14, 139, '2019/03/08', 'COMPARECEU', '+ / PARA LCA. US COM DICLOFENACO'),

(15, 156, '2019/01/20', 'COMPARECEU', 'US PULSADO, GELO E MOBILIZACAO LEVE'),

(16, 156, '2019/02/18', 'COMPARECEU', 'US DICLO, GANHO ADM, FORTALECIMENTO E GELO'),

(17, 156, '2019/03/08', 'COMPARECEU', 'US DICLO, GANHO ADM, FORTALE COM PESO, BIKE GELO '),

(18, 172, '2019/02/22', 'COMPARECEU', 'US DICLO, TIQ, KINESIO, IND ADM DE FLEXAO OMBRO '),

(19, 174, '2019/03/19', 'COMPARECEU', 'US DICLO. ALONGA E KINESIO FLEXORES DA MAO E'),

(20, 179, '2019/04/10', 'COMPARECEU', 'REALIZADO US CONTINUO COM DICLOFENACO
KINESIO TAPE EM RELAXAMENTO DE EXTENCAO DE HALUX E
MOBILIZACAO DE TORNOZELO E E INDICACAO DE MOVIMENTACAO E BOLSA DA AGUA QUENTE'),

(21, 180, '2019/04/23', 'COMPARECEU', 'ALONGAMENTO, FORCA DE CINTURA PELVICA E LOCOMOCAO COM MULETA.
PROPRIOCEPCAO PASSADA NO DISCO.
INDICACAO DE TREINO DE MARCHA COM MULETA E SAPATO COM ALTURA AJUSTADA
ATENDIMENTO DOMICILIAR'),

 (22, 180, '2019/04/05', 'COMPARECEU', 'US. ALONGAMENTO, FORCA DE CINTURA PELVICA E LOCOMOCAO'),

 (23, 180, '2019/04/09', 'COMPARECEU', 'US. ALONGAMENTO, FORCA DE CINTURA PELVICA E LOCOMOCAO COM MULETA'),

 (24, 123, '2019/04/12', 'COMPARECEU', 'PATELAS LATERALIZADAS E BAIXAS
DOR DE CONDROMALACIA EM AMBOS JOELHOS
ENCURTAMENTO MUSCULAR DE CADEIAS DE MMII
APLICADO US PULSADO COM DICLOFENACO
INDICACAO DE GELO
KINESIO DE CORRECAO PATELAR
INDICACAO DE ALONGAMENTOS DE CADEIA ANTERIOR E POSTERIOR DE MMII'),

 (25, 180, '2019/04/12', 'COMPARECEU', 'US. ALONGAMENTO, FORCA DE CINTURA PELVICA E LOCOMOCAO COM MULETA
ATENDIMENTO DOMICILIAR'),

 (26, 180, '2019/04/15', 'COMPARECEU', 'ALONGAMENTO, FORCA DE CINTURA PELVICA E LOCOMOCAO COM MULETA
ATENDIMENTO DOMICILIAR'),

 (27, 1, '2019/04/13', 'COMPARECEU', 'TESTE1'),

 (28, 1, '2019/04/14', 'FALTA A RECUPERAR', 'TESTE2'),

 (29, 1, '2019/04/15', 'RECUPERACAO', 'TESTE3'),

 (30, 123, '2019/04/22', 'COMPARECEU', 'APLICADO US PULSADO COM DICLOFENACO
INDICACAO DE GELO
KINESIO DE CORRECAO PATELAR
INDICACAO DE ALONGAMENTOS '),

 (31, 180, '2019/04/17', 'COMPARECEU', 'ALONGAMENTO, FORCA DE CINTURA PELVICA E LOCOMOCAO COM MULETA.
PROPRIOCEPCAO PASSADA NO DISCO.
INDICACAO DE TREINO DE MARCHA COM MULETA E SAPATO COM ALTURA AJUSTADA
ATENDIMENTO DOMICILIAR'),

 (32, 180, '2019/04/26', 'COMPARECEU', 'ALONGAMENTO, FORCA DE CINTURA PELVICA E LOCOMOCAO COM MULETA.
PROPRIOCEPCAO PASSADA NO DISCO.
INDICACAO DE TREINO DE MARCHA COM MULETA E SAPATO COM ALTURA AJUSTADA
ATENDIMENTO DOMICILIAR
OBS. NA QUARTA FEIRA TEVE DESEQUILIBRIO COM QUASE QUEDA AO DESCER DO DEGRAU ALTO. REALIZADO MENOS EXERCICIOS DE FORCA POIS ESTAVA COM UM POUCO DE DOR NO FEMUR E PROTESE'),

 (33, 156, '2019/04/26', 'COMPARECEU', 'FISIOTERAPIA APENAS PRA GANHO DE AMPLITUDE E US.
REALIZANDO GELO E MUSCULACAO PARA FORTALECIMENTO

ADM JOELHO DE FLEXAO DE 141GRAUS'),

 (34, 184, '2019/05/07', 'COMPARECEU', 'US PULSADO COM DICLOFENADO. KINESIO RELAXAMENTO ADUTOR E. E INDICACAO DE ALONGAMENTO ADUTOR E ANTERIOR DE COXA'),

 (35, 188, '2019/05/28', 'COMPARECEU', 'US CONTINUO COM DICLO. DISTENSIONAMENTO EM VARIOS PONTOS DE TENCAO ENTRE CERVICAL E OMBRO D E ENTRE CERVICAL E ESCAPULA D.
LIBERACAO MIOFASCIAL DA ESCAPULA. TRACAO E ALONGAMENTO DE PESCOCO E CERVICAL
KINESIO DE RELAXAMENTO ENRE OMBRO E CERVICAL E CERVICAL E ESCAPULA,
INDICACAO DE ALONGAMENTO CERVICAL E MOVIMENTO CIRCULARES DE PESCOCO E OMBROS, ASSIM COMO BOLSA DE AGUA QUENTE.

DIAGNOSTICO FISIOTERAPEUTICO
TENCAO MUSCULAR COM RIGIDEZ DEVIDO A SOBRECARDA DO ESPORTE'),

 (36, 188, '2019/06/07', 'COMPARECEU', 'US CONTINUO COM DICLO. DISTENSIONAMENTO EM VARIOS PONTOS DE TENCAO ENTRE CERVICAL E OMBRO D E ENTRE CERVICAL E ESCAPULA D.
LIBERACAO MIOFASCIAL DA ESCAPULA E PRINCIPALMENTE CLAVICULA ONDE FOI ENCONTRADO MAIOR CREPITACAO AO MOBILIZAR. TRACAO E ALONGAMENTO DE PESCOCO E CERVICAL
KINESIO DE RELAXAMENTO ENRE OMBRO E CERVICAL
INDICACAO DE ALONGAMENTO CERVICAL E MOVIMENTO CIRCULARES DE PESCOCO E OMBROS, ASSIM COMO BOLSA DE AGUA QUENTE.
TIQ CLAVICULA E OMBRO
DIAGNOSTICO FISIOTERAPEUTICO
TENCAO MUSCULAR COM RIGIDEZ DEVIDO A SOBRECARDA DO ESPORTE'),

 (37, 145, '2019/06/11', 'COMPARECEU', 'DOR LOMBAR FORTE APOS ANDAR DE CARRO NO DOMINGO ANTERIOR.

ULTIMA VERTEBRA LOMBAR/SACRO. US CONT + DICLO. TIQ, KINESIO DE RELAXAMENTO LOMBAR. ALONGAMENTO DE CADEIA POSTERIOR. '),

 (38, 194, '2019/06/19', 'COMPARECEU', 'INSTABILIDADE DE JOELHO E PERDA DE MASSA MUSCULAR EM ME
CLAUDICACAO COM COMPENSACAO DO TRONCO AO DEAMBULAR

US COM DICLO SUPERIOR E LATERAL OA JOELHO E
FLEXAO DE JOELHO PASSIVA
ELEVACAO DE MIE ATIVA E TREINO DE MARCHA'),

 (39, 189, '2019/06/21', 'COMPARECEU', 'IDENTIFACADO DOR MAIS SUPERIOR A INSERCAO DOS ISQUIOTIBIAS
MAIS LOMBAR BAIXA
US CONTI COM DICLO
TIG
DE}ISTENSIONAMENTO E ALONGAMENTO CADEIA POSTERIOR'),

 (40, 194, '2019/07/02', 'COMPARECEU', 'INSTABILIDADE DE JOELHO E PERDA DE MASSA MUSCULAR EM ME
CLAUDICACAO COM COMPENSACAO DO TRONCO AO DEAMBULAR

US COM DICLO SUPERIOR E LATERAL OA JOELHO E
FLEXAO DE JOELHO PASSIVA
ELEVACAO DE MIE ATIVA E TREINO DE MARCHA
AGACHAMENTO E KINESIO DE ESTABILIDADE JOELHO'),

 (41, 194, '2019/07/16', 'COMPARECEU', 'INSTABILIDADE DE JOELHO E PERDA DE MASSA MUSCULAR EM ME
CLAUDICACAO COM COMPENSACAO DO TRONCO AO DEAMBULAR

US COM DICLO SUPERIOR E LATERAL OA JOELHO E
FLEXAO DE JOELHO PASSIVA
ELEVACAO DE MIE ATIVA E TREINO DE MARCHA
MARCHA CARACTERISTI DE TRENDELEMBURG'),

 (42, 194, '2019/07/18', 'COMPARECEU', 'INSTABILIDADE DE JOELHO E PERDA DE MASSA MUSCULAR EM ME
CLAUDICACAO COM COMPENSACAO DO TRONCO AO DEAMBULAR

US COM DICLO SUPERIOR E LATERAL OA JOELHO E
FLEXAO DE JOELHO PASSIVA
ELEVACAO DE MIE, ABDUCAO, EXTENSAO POSTERIOR E ANTERIOR ATIVA E TREINO DE MARCHA E ABDUCAO COM ATIVACAO ELESTICO DE GLUTEOS'),

 (43, 196, '2019/07/19', 'COMPARECEU', 'TESTES DE LESAO LIGAMENTO E MENISCO NEGATIVOS.
GRANDE ENCURTAMENTO MUSCULAR DE CADEIDA POSTERIOR E RIGIDES DE MMII.
APLICACAO DE US CONTINUO INT DE 1,4
APLICACAO DE KINESIO PARA RELAXAMENTO DE ISQUIOTIBIAIS
ALONGAMENTO DE CADEIA POSTERIOR DE MMII E INDICACAO PRA FAZER EM CASA.'),

 (44, 198, '2019/08/13', 'COMPARECEU', 'LIMITACAO DO MSE EM ROTACOES E ABDUCAO E FLEXAO ACIMA DE 90.
APLICACAO DE US CONTINUO
DISTENSIONAMENTO
MOBILIZACAO DE OMBRO E ESCAPULA.
KINESIO DE RELAXAMENTO DE FLEXORES DO OMBRO.
INDICACAO DE CUIDADO DE MOV ACIMA DE 90 E INDICACAO DE COMPRESSA QUENTE AO DORMIR'),

 (45, 213, '2019/10/08', 'COMPARECEU', 'LESAO EM POSTERIOR D AO REALIZAR FLEXAO COM ADUCAO DO MID
US CONTINUO COM DICLOFENACO 
KINESIO TAPE DE RELAXAMENTO'),

 (46, 212, '2019/10/02', 'COMPARECEU', 'REFORMER'),

 (47, 212, '2019/10/09', 'COMPARECEU', 'CADILLAC'),

 (48, 216, '2019/10/15', 'COMPARECEU', 'TESTE DE HD NEGATIVO, POREM SENTE DOR NO CAMINHO DO CIATICO AO ALONGAR CADEIA POSTERIOR
A DOR LOCALIZA/SE MAIS NA VIRILHA E (TENDAO DOS ADUTORES) E ABDOMEM BAIXO, INSERCAO DO RETO E OBLICUOS.
PUBEITE OU IRADIACAO DE COMPRESSAO DA COLUNA?
TTO: US CONTINUO COM DICLOFENACO
KINESIO DE RELAXAMENTO EM ADUTORES E ABDOMEM INFERIOR E
INDICACAO DE ALONGAMENTO TODOS OS DIAS DE CADEIA POSTERIOR EM ABERTURA E ALONGAMENTO DE ADUTORES DA COXA BILATERAL

INDICACAO DE CONTINUIDADE DE TTO ATE 5 SESSOES

NECESSIDADE DE MELHORA PARA TERINAMENTO PARA CONCURSO DE AGENTE PENITENCIARIO TAF'),

 (49, 219, '2019/10/17', 'COMPARECEU', 'DOR LOMBAR BAIXA, TRANSICAO COM O QUADRIL, DO LADO DIREITO DA L5.
ALOMGAMENTO DE POSTERIOR DESSA PERNA UM POUCO PIOR
DOR AO VIRAR, RODAR
US CONTINUO COM DICLOFENACO
TIQ NAS VERTEBRAS LOMBARES
KINESIO DE RELAXAMENTO ENTRE INICIO DO SACRO ATE FINAL DA LOMBAR
INDICACAO DE ALONGAMENTO EM CASA, SERIE DE WILIANS ALTERNADO, ALONGAMENTO CADEIA POSTERIOR E MOBILIZACAO DE LOMBAR NA POSICAO SENTADO.'),

 (50, 216, '2019/10/24', 'COMPARECEU', 'TTO: US CONTINUO COM DICLOFENACO
KINESIO DE RELAXAMENTO EM ADUTORES E ABDOMEM INFERIOR E
INDICACAO DE ALONGAMENTO TODOS OS DIAS DE CADEIA POSTERIOR EM ABERTURA E ALONGAMENTO DE ADUTORES DA COXA BILATERAL

HA UNS TRES DIAS SENTIU GRANDE ALIVIO DA DOR, CONSEGUE FAZER MOVIMENTO LESIVO QUASE SEM DOR
AO VIRAR NA CAMA SENTE UM PEQUENO DESCONFORTO, ESPREGUICAR E ENTRAR NO CARRO

INDICACAO DE INICIO DE TREINO COM CUIDADOS E GELO LOGO APOS'),

 (51, 216, '2019/11/06', 'COMPARECEU', 'TTO: US CONTINUO COM DICLOFENACO
KINESIO DE RELAXAMENTO EM ADUTORES E ABDOMEM INFERIOR E
INDICACAO DE ALONGAMENTO TODOS OS DIAS DE CADEIA POSTERIOR EM ABERTURA E ALONGAMENTO DE ADUTORES DA COXA BILATERAL

JA ESTA CORRENDO SEM DOR
APENAS DOR LEVE AO ESPREGUICAR NO ABDOMEM INFERIOR E'),

 (52, 220, '2019/11/08', 'COMPARECEU', 'DOR EM TORNOZELO ESQUERDO COM INCHACO PRINCIPALMENTE AO CORRER, COLOCA GELO ALIVIA

US COM DICLOFECNADO, NO FIBULAR LONGO E MALEOLO LATERAL
KINESIO DE RELAXAMENTO DO MUSCULO E DE PODISIONAMENTO DO PE PARA CORRECAO DO SUPINADO'),

 (53, 224, '2019/12/06', 'COMPARECEU', 'ESSE ANO SENTIU UM ESTIRANDO COM DOR NO ANTERIOR DA COXA D
TODAS AS VEZES PARA DE JOGAR E RETORNA AO MELHORAR E ACONTECE NOVAMENTE
A DOR ACONTECE SO AO JOGAR FUTEBOL E NA CONTRACAO ISOMETRICA

TTO: US CONTINUO COM DICLO QUADRICEPS PORCAO MEDIA E LATERAL
KINESIO DE RELAXAMENTO PARA AMBOS
E KINESIO DE CORRECAO PARA TORNOZELO QUE SUPINA 

INDICACAO DE ALONGAMENTO E MUSCULACAO'),

 (54, 225, '2019/12/06', 'COMPARECEU', 'DOR EM ANTEIRIOR DO TORNOZELO E (TIBIAL?), AO FAZER A PLANTI FLEXAO. VINHA A ALGUM TEMPO SENTINDO E MELHORAVA, AGORA VEM SENTINDO COM FREQUENCIA.

A ALGUM TEMPO DEU UM CHUTE COM PONTA DE PE NO FUTEBOL E SENTIU ESSA DOR, MELHOU E AGORA VEM SENTINDO COM MAIS FREQUENCIA
DOR LEVE COM PERIODOS MAIS AGUDOS.

SUGETIVO DE LESAO ANTIGA DOS FLEXORES DORSAIS DO PE ESQUERDO, PROXIMO AO TENDAO, POSSIVEIS CALCIFICACOES
ARCO DO PE ESQUERDO MAIS DESABADO, HIPERFLEXIBILIDADE

TTP: KINESIO DE RELAXAMENTO PARA ESSE GRUPO MUSCULAR E DE ESTABILIZACAO DE TORNOZELO
US CONTINUO COM DICLO. PARA INFLAMACAO
INDICACAO DE SEQUENCIA DE FORTALECIMENTO PARA REPOSICIONAMENTO DO PE, COM FLEXAO PLANTAR E DORSAL E DEDOS LENTO E CONSCIENTE PARA CORRECAO DO MOVIMENTO.'),

 (55, 224, '2019/12/10', 'COMPARECEU', 'TTO: US CONTINUO COM DICLO QUADRICEPS PORCAO MEDIA E LATERAL
KINESIO DE RELAXAMENTO PARA AMBOS
E KINESIO DE CORRECAO PARA TORNOZELO QUE SUPINA
+ KINESIO DE RELAXAMENTO PARA OBLIQUO INFERIOR E PSSOAS 
INDICACAO DE GELO APOS JOGO DE FUTEBOL

INDICACAO DE ALONGAMENTO E MUSCULACAO

RETORNO: SENTIU DOR NO ULTIMO JOGO, POREM JOGOU E NAO SENTIU DOR DEPOIS'),

 (56, 226, '2019/12/11', 'COMPARECEU', 'BEM NA LATERAL SUPERIOR DO QUADRIL, CRISTAS ILIACAS EM AMBOS OS LADOS

DIAGNOSTICO FISIO: APARENTE INFLAMACAO NAS BURSAS TROCANTERICAS POR DESCARGA DE PESO ALTERADA APOS FRATURA DE TARSOS EM PE ESQUERDO.

TTO: US CONTINUO COM DICLOFENACO, KINESIO DE RELAXAMENTO VERTICAL, TIQ CRISTAS ILIACAS E FEMUR, EXERCICIO DE CONSIENTIZACAO E FORTALECIMENTO PARA REEDUCAR MOVIMENTO DE TORNOZELO, PE E DEDOS. INDICACAO DE GELO APOS ATIVIDADES E INDICACAO DE RETORNO SE HOUVER AINDA DOR.'),

 (57, 223, '2019/12/05', 'COMPARECEU', 'LESAO DE INTERNO DE COXA D EM UM LANCE AO JOGAR FUTEBOL
EDEMACIADO, DOR NA PALPACAO E DIFICULDADE DE ANDAR

TTO: MEDIDADAS ANTIINFLAMATORIAS, GELO E ULTRASSOM COM DICLOFENACO
KINESIO TAPE DE REXAXAMENTO DA MUSCULATURA AFETADA
ALONGAMENTO DE CADEIA POSTERIOR

INDICACAO DE PAUSA NO ESPORTE ATÉ A MELHORA

INDICACAO DE MUSCULACAO PARA EVITAR NOVAS LESOES
INDICACAO DE ALONGAMENTOS OU PILATES NO PÓS FASE AGUDA.'),

 (58, 223, '2019/12/12', 'COMPARECEU', 'LESAO DE INTERNO DE COXA D EM UM LANCE AO JOGAR FUTEBOL
EDEMACIADO, DOR NA PALPACAO E DIFICULDADE DE ANDAR

TTO: MEDIDADAS ANTIINFLAMATORIAS, GELO E ULTRASSOM COM DICLOFENACO
KINESIO TAPE DE REXAXAMENTO DA MUSCULATURA AFETADA
ALONGAMENTO DE CADEIA POSTERIOR

RELATO DA SEMANA: SENTIU GRANDE MELHORA PRINCIPALMENTE PARA CAMINHAR
DIMINUICAO SIGNIFICATIVA DO INCHACO
'),

 (59, 224, '2019/12/13', 'COMPARECEU', 'REAPLICACAO DE KINESIOTAPE PARA MESMO TRATAMENTO, JOGO A NOITE'),

 (60, 227, '2019/12/13', 'COMPARECEU', 'DOR NA FLEXAO DO OMBRO D COM UM POUCO DE ABDUCAO, PONTO DE DOR BEM NO TENDAO DO INFRA ESPINHAR

ULTRASSOM CONTINUO COM DICLO NOS PONTOS DE INSERCAO DOS TENDOS DO OMBRO NA CABECA DO FEMUR, PROXIMO AO ACROMIO
KINESIO TAPE DE RELAXAMENTO NO INFRA ESPINHAL E NO BICEPS LATERAL

PALPACAO DA MUSCULATURA CERVICAL E TRAPEZIOS NORMAL

INDICACAO DE BOLSA DE AGUA QUENTE E RETORNA NA FISIO, ASSIM COMO CONSULTA MEDICA PARA DIAGNOSTICO MEDICO.'),

 (61, 227, '2019/12/18', 'COMPARECEU', 'DOR NA FLEXAO DO OMBRO D COM UM POUCO DE ABDUCAO, PONTO DE DOR BEM NO TENDAO DO INFRA ESPINHAR

ULTRASSOM CONTINUO COM DICLO NOS PONTOS DE INSERCAO DOS TENDOS DO OMBRO NA CABECA DO FEMUR, PROXIMO AO ACROMIO
KINESIO TAPE DE RELAXAMENTO NO INFRA ESPINHAL E NO BICEPS LATERAL

MOBILIZACAO DE ESCAPULA

MELHORA DA DOR, INDICACAO DE MAIS UMA SESSAO');