INSERT INTO AVALIACAO (COD, CODALUNO, PROFISSAO, INDICACAO, ATIVIDADEFISICA, QUALATIVIDADEFISICA, MEDICACAO, TABAGISMO, ETILISMO, HIPERTENSAO, DOENCAS, DORES, POSICAODOR, OBJETIVOPRINCIPAL, QUEIXAPRINCIPAL, PESO, ALTURA, PA, ENCURTAMENTOS, FORCAMUSCULAR, PES, JOELHOS, PELVE, COLUNA, OMBROS, ESCAPULAS, CABECA)
VALUES
(1, 1, 'QUALIDADE', 'MÉDICO', 'NÃO', '-', '-', 'NÃO', 'NÃO', 'NÃO', '-', 'LOMBAR SACRA COM IRRADICAO PARA PERNA DIREITA E ATUALMENTE ESQUERDA TAMBÉM.
DOR ESCAPULAR MEDIALMENTE DO LADO E. IRRADIA PARA TRAPÉZIOS
JOALHOS EVENTUALMENTE', 'MMII NA POSICAO SENTADA E AO ACORDAR DE MANHA
ESCAPULAR E OMBRO AO TRABALHO', 'CONTROLE DA DOR', 'LOMBAR', 98, 1.79999995231628, NULL, 'CADEIA POSTERIOR (MEDIANO)', 'FRAQUEZA ABDOMINAL/CORE', 'APOIO LATERAL', 'ALINHADOS', 'RETROVERTIDA', 'LOMBAR RETIFICA', 'RI E ASSIMILARE', 'ADERIDAS', 'ANTERIORIZADA'),

(2, 2, 'ESTUDANTE', 'MEDICO E OUTROS', 'SIM', 'DANCA 3X POR SEMANA
FUTEBOL 1 X POR SEMANA', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'ESCOLIOSE', 'NÃO', 'NÃO', 'DIMINUICAO E ESTABILIZACAO DA ESCOLIOSE', 'ESCOLIOSE', NULL, NULL, NULL, 'FLEXAO DE TRONCO', 'FRAQUEZA ANTERIOR DE TRONCO, CORE', 'OPOIO LATERAL', 'LEV VALGOS', 'ANTEVERSAO', 'ASSIMETRICA', 'ASSIMETRICOS', 'ASSIMETRICAS', 'ALINHADA'),

(3, 3, 'PROFESSORA', 'MEDICO', 'SIM', 'PILATES', 'TRAMADOL, ANELGESICOS E P FRIBROMIALGIA', NULL, NULL, NULL, 'HD
FIBROMIALGIA', 'LOMBO SACRA, IRRADIA PARA MID
QUADRIL
DORES FIBROMIALGICAS (ARTICULARES GERAIS)
DOR OMBROS, MAIOR EM D', 'MOVIMENTOS REPETITIVOS E MOVIMENTOS BRUSCOS COM SENSACAO DE TRAVAMENTO', 'REDUCAO DAS DORES E ATIVIDADE FISICA', 'DOR LOMBO SACRA', NULL, NULL, NULL, 'OTIMO ALONGAMENTO, REDUZ EM CRISES DE DOR', 'FRAQUEZA DE FORMA GERAL, PRINCIPALMENTE CORE', 'RE, CALCANEOVAL', 'VALGOS', 'ANTEVERTIDA', 'HIPERLORDOSE', 'ASSIMETRICOS', 'ADERIDAS', 'HIPEREXTENCAO'),

(4, 4, 'ESTUDANTE', 'MEDICO', 'SIM', 'PILATES', 'NÃO', 'NÃO', 'NÃO', 'NÃO', 'INTOLERANCIA A LACTOSE
ESCOLIOSE', 'EVENTUALMENTE LOMBAR', 'EM PE', 'CONTROLAR ESCOLIOSE', 'ESCOLIOSE', 53, 1.62999999523163, NULL, 'FALTA DE MOBILIDADE COLUNA, ALONGAMENTO POSTERIOR OTIMO', 'FRAQUEZA DE MUSCULATURA DE TRONCO', 'SUPINADOS', 'LEV VAROS', 'ASSIMETRICA', 'ASSIMETRICA', 'ASSIMETRICOS', 'ABDUZIDAS', 'ALINHADA'),

(5, 5, 'EMPRESSARIA', 'OUTROS', 'SIM', 'PILATES E BIKE', 'NÃO', NULL, NULL, NULL, 'NÃO', 'EVENTUALMENTE TRAPEZIO', 'SENTADA COSTURANDO', 'ATIV FISICA', 'TRABALHAR ABDOMEN E PERNAS', NULL, NULL, NULL, 'CADEIA POSTERIOR, GRANDE ENCURTAMENTO', 'FRAUQEZA DE FORMA GERAL, SEDENTARISMO', NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(6, 6, 'RECURSOS HUMANOS ADM', 'MEDICO', 'SIM', 'PILATES E CAMINHADA', 'ALNALGESICOS EVELTUALMENTE', NULL, NULL, NULL, 'NÃO', 'LOMBAR LOCALIAZADA', 'SENTADA E DEITADA', 'DIMINUIR A DOR E ATIV FISICA', 'DOR LOMBAR', NULL, NULL, NULL, 'CADEIA POSTERIOR', 'FRAQUEZA MUSC DE FORMA GERAL, PRINCIPALMENTE CORE', NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(7, 7, 'ADVOGADA', 'FISIO SONIA', 'SIM', 'PILATES E MUSCULACAO', 'NÃO', NULL, NULL, NULL, 'INTOLERANCIA A LACTOSE', 'NÃO', 'NÃO', 'POSTURAL', 'MA POSTURA', NULL, NULL, NULL, 'BOM', 'BOA', 'LEV PRONADOS', 'VALGOS', 'LEV ANTEVERTIDA', 'ASSIMETRICA E H', 'LEV RI', 'ABDUZIDAS', 'LEV ANTERIOR'),

(8, 8, 'APOSENTADO', 'MEDICA', 'NÃO', NULL, NULL, NULL, NULL, NULL, 'PARKINSON', 'JOELHOS E EVENTUAL LOMBAR E OMBRO', 'AO ANDAR', 'DIMINUIR DORES E MANUTENCAO DA ADM', 'DOR JOELHOS', NULL, NULL, NULL, 'BASTANTE ENCURTAMENTO DE TODAS CADEIAS MUSCULARES, ADMS REDUZIDAS', 'FRAQUEZA MUSCULAR GERAL E SEDENTARISMO', 'PRONADOS', 'VAROS', 'NEUTRA E ASSIME', 'HIPER CIFOSE D', 'RI', 'RETIFICADAS', 'ANTERIOZIZADA'),

(9, 9, 'PEDREIRO', 'FISIO CARLOS INDAIAL', 'SIM', 'FUTEBOL E BIKE', 'NÃO', NULL, NULL, NULL, 'NÃO', 'LOMBAR IRRADIADA PARA MIE
OMBRO D', 'AGACHADO E FLEXIONADO E AO ACORDAR', 'CONTROLE DA DOR E HD', 'HD LOMBAR', NULL, NULL, NULL, 'CADEIA POSTERIOR LEVE', 'FRAQUEZA CORE', 'SUPINADOS', 'VAROS', 'RETROVERTIDA', 'RETIFICADA', 'RI', 'ADERIDAS', 'RETIFICADA'),

(10, 10, 'ADVOGADA', 'OUTROS', 'SIM', 'PILATES', 'NÃO', NULL, NULL, NULL, 'ESCOLIOSE', 'POSTURAIS', 'SENTADA', 'POSTURAL', 'POSTURAL', NULL, NULL, NULL, 'CADEIA POSTERIOR', 'FRAQUEZA DE MODO GERAL. A POUCO TEMPO SEDENTARISMO', NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(11, 11, 'EMPRESARIA', 'OUTROS', 'SIM', 'PILATES', 'SUPLEMENTACAO ORTOMOLECULAR', NULL, NULL, NULL, 'NÃO', 'LOMBAR E PÉ', 'LOMBAR AO CAMINHAR
PE AO USAR CERTOS CALCADOS', 'ATIV FISICA', 'LOMBAR', NULL, NULL, NULL, 'CADEIA POSTERIOR', 'BOA', NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(12, 12, 'ADVOGADA ESTUDANDO', 'MEDICO OUTROS', 'SIM', 'PILATES E MUSCULACAO', 'ANALGEZICOS', NULL, NULL, NULL, NULL, 'LOMBAR IRRADIADA MI', 'VARIAS', 'REDUCAO DA DOR E CONTROLE HD', 'DOR HD', NULL, NULL, NULL, 'CADEIA POSTERIOR', 'FRAQUEZA DE MODO GERAL', 'SUPINADOS', 'LEV VALGOS', 'ANTEVERSAO', 'HIPER LORDOSE', 'RI', 'ALINHADAS', 'ANTERIORIZADA'),

(13, 13, 'PROFESSORA APOSENTADA', 'OUTROS', 'SIM', 'PILATES MUSCULACAO E BIKE', NULL, NULL, NULL, NULL, NULL, 'LOMBAR E CERVICAL', 'AO PEDALAR', 'REDUCAO DA DOR MANUTENSAO DE ADM', 'DOR LOMBAR', NULL, NULL, NULL, 'CADEIA POSTERIOR MODERADO', 'FRAQUESA DO CORE', NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(14, 14, 'APOSENTADA', 'MEDICA OUTRAS', 'SIM', 'PILATES', 'SIM, VARIOS', NULL, NULL, 'SIM', 'HIPERTENSAO, ATEROSCLEROSE, ARTROSE', 'JOELHOS, EVENTUALEMNTE LOMBAR', 'AO ANDAR', 'AMENISAR DORES NOS JOELHOS E QUALIDADE DE VIDA', 'DOR JOELHOS', NULL, NULL, NULL, 'CADEIA POSTERIOR E ANTERIOR', 'FRAQUEZA DE MODO GERAL, PRINCIPALMENTE QUADRICEPS E GLUTEOS', 'SUPINADOS', 'VALGO E VARO', 'ANTEVERTIDA', 'LEV HIPERLORDOS', 'RI', 'ADERIDAS', 'NEUTRA'),

(15, 17, 'CABELEREIRA', 'CONTA PROPRIA', 'SIM', 'PILATES E BIKE', 'FRIBROMIALGIA - VILIGIA
PREGABALINA', NULL, NULL, NULL, 'FIBROMIALGIA
DESGASTES E HD', NULL, NULL, NULL, NULL, 98, 1.75, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(16, 88, 'ESTUDANTE, ADVOGADA', 'ANDREIA FRAINER', 'SIM', 'PILATES E TAIFIT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 80, 1.70000004768372, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(17, 168, 'DO LAR', 'MEDICO', 'NÃO', NULL, 'REMEDIOS PARA DOR', 'SIM', NULL, 'NÃO', NULL, 'DOR LOMBAR E MIE', 'MAIS DOLORIDO AO SENTAR E LEVANTAR', 'ALIVIAR A DOR', 'DOR COLUNA E MIE', 64, 1.51999998092651, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(18, 167, 'MANICURI', 'JANETE WANDERVERGUER', 'SIM', 'PILATES E FUNCIONAL PERSONAL', NULL, NULL, NULL, NULL, NULL, 'DOR NO OMRBO D E COLUNA LOMBAR', 'DOR NA POSICAO PARADA... DORMINDO', 'ALIVIAR AS DORES E QUALIDADE DE VIDA', 'DOS COLUNA E OMBRO', 70, 1.60000002384186, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(20, 170, 'APOSENTADA DO LAR', 'MEDICO', 'NÃO', NULL, 'ANALGESICOS', NULL, NULL, NULL, NULL, 'MMII', NULL, NULL, NULL, 80, 1.70000004768372, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(19, 169, 'SUPERVISORA DE EXPORTACAO', 'IVONETE CESCON', 'SIM', 'ACADEMIA PERSONAL E PILATES', 'ANTICONCECIONAL', NULL, NULL, NULL, 'ESCOLIOSE CONVEXIDADE A D', NULL, NULL, 'POSTURA E ALONGAMENTO', 'POSTURAL', 65, 1.73000001907349, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(21, 171, 'EMPRESARIO', NULL, 'SIM', 'MUSCULACAO E FUTEBOL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(22, 139, 'ATLETA E ESTUDANTE', 'TREINADORA', 'SIM', 'TREINOS DE CORRIDA E MUSCULACAO
CORRIDA FUNDISTA E VELOCIDADE', NULL, NULL, NULL, NULL, NULL, 'JOELHOS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ANTEVERTIDA', NULL, NULL, NULL, NULL),

(23, 156, 'MOTORISTA', 'MEDICO', 'SIM', 'FUTEBOL E MUSCULACAO', 'NÃO', NULL, NULL, NULL, 'ESPONDILOLISE LOMBAR
LESAO LCA E MENISCO D', 'JOELHO', NULL, NULL, NULL, 76, 1.83000004291534, '130X80', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(24, 172, 'APOSENTADO', 'FILHO', 'NÃO', NULL, NULL, NULL, NULL, NULL, NULL, 'OMBRO IRADIA PARA PESCOCO', 'AO ERGUER O BRACO E AO DEITAR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(25, 174, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(26, 175, 'ADMINISTRATIVO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'HIPEREXTENSAO', NULL, NULL, NULL, NULL, NULL),

(27, 177, 'APOSENTADA', 'MEDICO', 'SIM', NULL, NULL, NULL, NULL, NULL, NULL, 'DOR LOMBAR E QUADRIL', 'AO LIGAR A MOTO', 'ALIVIAR A DOR E ATIVIDADE FISICA', NULL, 66, 1.66999995708466, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(28, 178, 'FAXINEIRA', 'PATROA', 'NÃO', NULL, NULL, NULL, NULL, NULL, NULL, 'OMBROS QUE IRADIAM PARA OS MMSS.
DORES NAS PERNAS', 'AO DESCANCAR E DORMIR', 'ALIVIO DA DOR NOS OMBROS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(29, 179, NULL, NULL, NULL, NULL, NULL, 'NÃO', 'NÃO', 'NÃO', 'RETARDO MENTAL
REFLUXO MODERADO DE VASOS PROFNDO EM MMII', 'DOR ANTERIOR NO PÉ E E EM HALUX', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(30, 180, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(31, 123, NULL, NULL, 'SIM', 'BIKE 4X POR SEM', NULL, NULL, NULL, NULL, 'CONDROMALACIA MMII', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(32, 182, 'APOSENTADA PROFESSORA', 'IRIA', 'NÃO', NULL, 'TIREOIDE', NULL, NULL, NULL, NULL, 'DOR PANTURILHA E DE ORIGEM LOMBAR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(33, 184, 'ED FISICO', NULL, NULL, 'FUTEBOL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(34, 185, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(35, 186, 'APOSENTADA', 'FILHAS', NULL, NULL, 'CONDOR, ELIQUIS, PARACETAMOL, OS-CAL, GLIFAGE, TREZOR, ALDACTONE, ALENIA', 'NÃO', 'NÃO', 'NÃO', 'CORACAO, DIABETES, COLESTEROL ARITMIA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(36, 187, 'APOSENTADA COSTUREIRA', 'AMIGA', 'NÃO', NULL, 'CALCIO
VITAMINAS', NULL, NULL, NULL, 'CALCIFICACAO NO SEIO
OSTEOPOROSE', 'COLUNA LOMBAR E OMBRO E', 'AO FAZER FAXINA E SERVICO DE CASA', 'ILIVIO DAS DORES, ALONGAMENTO', 'DOR LOMBAR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(37, 188, 'ESTUDANTE E ATLETA', NULL, NULL, 'ATLETA LANCAMENTO DE DARDO E PESO
FUTSAL E VOLEI DE QUADRA', NULL, NULL, NULL, NULL, NULL, 'CERVICAL E OMBRO D', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'AO FAZER MOVIMENTO DE CINTURA ESCACUPAR FOI OBSERVADO CREPIDACAO NA MUSCULATURA', NULL, NULL),

(38, 189, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ABAIXO DOS GLUTEOS E POSTERIORES BILATERALMENTE', 'PRINCIPALMENTE AO SENTAR E LEVANTAR', 'ALIVIO DA DOR', 'DOR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(39, 190, 'APOSENTADO', NULL, NULL, NULL, 'PRESSAO', NULL, NULL, NULL, 'TUMOR INTESTINAL OPERADO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(40, 191, 'ESCREVENTE', 'DR FERNANDO RASUMURA', 'NÃO', NULL, NULL, 'NÃO', 'NÃO', 'NÃO', 'FIBROMIALGIA', 'GERAIS, OMBROS, BRACO, QUADRIL E JOELHOS', 'AO DORMIR E PRINCIPALMENTE A ACORDAR COM SENSACAO DE TRAVAMENTO', 'ALIVIO DAS DORES', 'DORES E TRAVAMENTO', 73, 1.75, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(41, 192, 'COMERCIANTE', NULL, 'SIM', 'PILATES', NULL, NULL, NULL, NULL, 'INTOLERANCIA A LACTOSE', 'LADO D, BURSITE OMBRO D, E DOR LATERAL DO QUADRIL', NULL, 'ALIVIO DAS DORES E ATIVIDADE FISICA', 'DORES E GERAIS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(42, 193, 'ESTUDANTE', 'PEDIATRA', 'SIM', 'FUTEBOL 2X POR SEM
PILATES 1X POR SEM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MELHO DA POSTURA', 'MA POSTURA', 58.7999992370605, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(43, 194, 'AJUDANTE DE MOTORISTA', 'MEDICA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SUPERIOR NO JOELHO OPERADO E. FINAL DO QUADRICEPS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(44, 195, 'APOSETADA - PROFESSORA', 'MEDICO', 'NÃO', NULL, 'CALCIO, ALENDRONATO, ENTRESTO - INSUFICIENCIA CARDIACA, CARDIVILOL, ESPIRONOLACTONA, FURASEMIDA, ALDAGTONI, BUPRORPIONA - ANSIEDADE, ASPIRINA', NULL, NULL, NULL, 'LINFOMA DE GANGLIO - CURADO
INSUFICIENCIA CARDIACA EM 40%', 'DOR NO JOELHO D E COLUNA LOMBAR-TORACICA', 'AO CAMINHAR MAIS
SERVICOS DOMESTICOS AO ABAIXAR', 'GANHO MUSCULAR
ALINHAMENTO DE POSTURA
ALIVIO DAS DORES', NULL, NULL, NULL, NULL, NULL, 'EXTREMAMENTE DIMINUIDA EM EM MMII E GLUTEOS', NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(45, 196, 'APOSENTADO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'AO FLEXIONAR JOELHOS', 'ALIVIO DA DOR', NULL, NULL, NULL, NULL, 'GRANDE ENCURTAMENTO MUSCULAR DA CADEIA POSTERIOR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(46, 197, 'ESTUDANTE', NULL, 'SIM', 'PILATES
EDUCACAO FISICA
MUSCULACAO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 47, 1.53999996185303, NULL, NULL, 'TREMOR AOS MOVIMENTOS DE FORCA', NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(47, 198, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(48, 199, 'EMPRESARIO', NULL, 'SIM', 'MUSCULACAO E BIKE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ANTEVERTIDA', NULL, 'ANTERIORIZACAO E SUPERIORIZACAO DE OMBROS E ESCAPULA', NULL, NULL),

(49, 200, 'DESINER', 'IVANETE BUZZI', 'SIM', 'BIKE', 'PURAN', 'NÃO', 'NÃO', 'NÃO', 'HIPOTIREODISMOS', 'EVENTUALMENTE TENSAO EM OMBROS E PESCOCO', 'NO TRABALHO', 'INICIAR ATIVIDADE FISICA', NULL, 48, 162, NULL, 'GRANDE ENCURTAMENTO MUSCULAR DE MODO GERAL', 'FRAQUEZA GERAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(50, 201, 'PEDREIRO', 'MEDICA', 'NÃO', NULL, NULL, NULL, NULL, NULL, 'FIBROMIALGIA', 'COLUNA E OMBROS', NULL, 'ALIVIO DAS DORES', 'DOR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(51, 202, 'NUTRICIONISTA', NULL, 'SIM', 'PILATES', NULL, NULL, NULL, NULL, NULL, 'EM MSD AO AMAMENTAR', 'AO CARREGAR AS FILHAS', 'ATIVIDADE FISICA', NULL, 57, 168, NULL, 'ENCURTAMENTO DE CADEIA POSTERIOR SIGNIFICATIVO', 'DIMINUIDA EM TODOS GRUPOS MUSCULARES', NULL, NULL, 'NEUTRA', 'POUCA MOBILIDADE', 'TENSAO DE OMBROS, COM ELEVACAO DE OMBROS E ESCAPULA', NULL, NULL),

(52, 203, 'ESTUDANTE', 'MEDICO', 'NÃO', NULL, NULL, NULL, NULL, NULL, NULL, 'FINAL TORACICA E LOMBAR', 'EM PE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(53, 138, 'NUTRICIONISTA', NULL, 'SIM', 'CORRIDA E MUSCULACAO', 'ANTICONCEPCIONAL', 'NÃO', 'NÃO', 'NÃO', NULL, 'DOR EM JOELHO E
TENDAO DE AQUILES E', 'EVENTUALEMENTE NA CORRIDA, APOS PROVAS', 'ALIVIO DAS DORES', 'DOR NO TENDAO', 59, 167, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(54, 207, 'VENDEDORA', 'NUTRICIONISTA', 'SIM', 'CORRIDA E MUSCULACAO', NULL, NULL, NULL, NULL, NULL, 'TORNOZELO E', 'AO FAZER ESTEIRA', 'ALIVIO DAS DORES', 'DOR TORNOZELO', 56, 159, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(55, 208, 'VIGILANTE', 'DR FABIO SOEJIMA', 'NÃO', NULL, NULL, 'NÃO', 'NÃO', 'SIM', NULL, 'DOR CERVICAL IRRADIADA PARA TORAX E MSE
DOR LOMBAR BAIXA QUE JA IRRADIOU PARA MID', 'CERVICAL DOI DURANTE O TRABALHO
LOMBAR DOR IRADIADA AO FICAR EM PE', 'ILIVIO DAS DORES', 'DOR NA CERVICAL', 93, 179, NULL, 'GRANDE ENCURTAMENTO E POSTURA DESALINHADA', 'FRAQUEZA DE TRONCO', NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(56, 211, 'BIOMEDICA ESTETICA', 'PERSONAL', 'SIM', 'MUSCULACAO COM PERSONAL', NULL, 'NÃO', 'NÃO', 'NÃO', NULL, 'LOMBAR, JOELHO D (CARTILAGEM)', 'POUCO FRENQUENTE', 'AVALIACAO POSTURAL PARA MUSCULACAO', NULL, 59, 172, NULL, 'CADEIA ANTERIOR DE TRONCO SEM ENCURTAMENTO
CADEIA POSTERIOR DE MMII E TRONCO ENCURTADO', '-', 'CALCANEOS LEVEMENTE VALGOS', 'ALINHADOS
TESTE DE COMPRESSAO PATELAR POSITIVO
SUGESTIVO DE CONDROMALACEA
SEM CREPITACAO', 'ALINHADA ENTERIO-POSTERIOR
CRISTA ILICA ESQUERDA ELEVADA', 'ESCOLIOSE CONVEXA A ESQUERDA
CIFOSE TORACICA LEVEMENTE AUMENTADA
TESTES DE COMPRESSAO DE RAIZ NERVOSA NEGATIVOS', 'RODADOS INTERNAMENTE E ESQUERDO ELEVADO EM RELACAO AO DIREITO', 'ESQUERDA UM POUCO MAIS ABDUZIDA EM RELACAO A DIREITA', 'ANTERIORIZADA'),

(57, 209, 'ESTETICA', 'PERSONAL', 'SIM', 'MUSCULACAO COM PERSONAL', NULL, 'NÃO', 'NÃO', 'NÃO', NULL, 'OMBRO E POSTERIORMENTE', 'AO REALIZAR MOVIMENTOS  DE FLEXAO E ABDUCAO ACIMA DE 90 GRAUS', 'AVALIACAO PRA PERSONAL', NULL, 59.7999992370605, 170, NULL, 'BOM ALONGAMENTO DE CADEIA POSTERIOR E ANTERIOR
RIGIDES LOMBAR (ULTIMAS VERTEBRAS)', '-', 'CALCANEO VALGO', 'VALGOS
TESTES DE COMPRESSAO, MENISCO E LIGAMENTOS NEGATIVOS', 'ANTEVERSAO  E CENTRO DE GRAVIDADE NA PELVE ANTERIORIZADO', 'HIPERLORDOSE LOMBAR
HIPERCIFOSE TORACICA
TESTES DE COMPRESSAO DE RAIZ NERVOSA NEGATIVOS
TESTE DE COMPRESSAO DE L5 COM DESCONFORTO', 'TESTES DE ROTACAO E FLEXAO  E EXTENSAO NORMAIS, LEVE DESCONFORTO AO FINAL DO MOVIMENTO DE RI E FLEXAO', 'ABDUZIDAS', 'ANTERIORIZADA'),

(58, 212, 'ASSESORA DO PROMOTOR', 'MEDICO', 'NÃO', NULL, NULL, 'NÃO', 'NÃO', 'NÃO', NULL, 'JOELHOS ABAIXO DA PATELA E INTERNA', 'SENTADA
DIFICULDADE DE DOBRAR OS JOELHOS', 'ALIVIO DA DOR', 'DOR JOELHOS', 43, 157, NULL, 'ENCURTAMENTO DE CADEIA POSTERIOR', 'DIMINUIDA DE MODO GERAL', NULL, 'VAROS, PORÉM AO FELXIONAR TEM VALGO DINAMICO', NULL, 'ESCOLIOSE
CIFOSE TORACI AUMENTADA', 'PROTRUSOS', NULL, NULL),

(59, 213, 'SUPERVISOR DE CAIXA', 'ANDERSON ACADEMIA', 'SIM', 'FUTEBOL E MUSCULACAO', 'ANTIINFLAMATORIO PARA LESAO', NULL, NULL, NULL, NULL, '09.10.19
A 15 DIAS ATRAZ FISGADA EM POSTERIOR D
DEPOIS DE TOMAR ANTIINFLAMATORIO SINTIU MELHORA E AO JOGAR SENTIU POSTERIOR D NOVAMENTE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(60, 214, 'EMPRESARIA', 'MEDICO', 'NÃO', NULL, 'PURAN', NULL, NULL, NULL, 'HIPOTIREODISMO', 'CERVICAL', 'DESCONFORTO AO ASSISTIR TV SENTADA TRABALHANDO', 'ALIVIO DAS DORES E ATIVIDADE FISICA', 'DOR CERVICAL', 68, 1.64999997615814, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(61, 215, 'EMPRESARIO', 'MEDICO', 'NÃO', NULL, 'PARA DIABETES', NULL, NULL, NULL, 'DIABETES
DISCOPATIA DEGENERATIVA DE COLUNA LOMBAR
TENDINITE DE OMBRO D
SINDROME DO TUNEL DO CARPO DE PUNHO D', 'LOMBAR QUE IRRADIA PARA AMBOS MMII
TORACICA
OMBRO D E PUNHO DIREITO COM FORMIGAMENTO', 'AO DORMIR
PARADO NA MESMA POSICAO POR MUITO TEMPO', 'ALIVIO DAS DORES E MANTER MOVIMENTOS', 'DORES COLUNA E MSD', 93, 1.6599999666214, NULL, 'CADEIA POSTERIOR PRINCIPALMENTE', 'PRINCIPALMENTE DE ABDOMEM', NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(62, 216, 'AGENTE PENITENCIARIO', NULL, 'SIM', 'MUSCULACAO
JOGANDO VOLEI', 'ANTIINFLAMATORIO PARA DOR', NULL, NULL, NULL, NULL, 'VIRILHA ESQUERDA IRADIANDO PARA BARRIGA', 'AO CORRER E AO ESPREGUICAR DE MANHA', 'ALIVIO DA DOR', 'DOR VIRILHA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(63, 217, 'ESTUDANTE', 'DR FABIO SOEJIMA', 'SIM', NULL, NULL, NULL, NULL, NULL, NULL, 'LOMBAR BAIXA', 'AO DORMIR
AO CAMINHAR MUITO
AO LEVANTAR RAPIDO', 'ALIVIO DA DOR PARA EVITAR ARTRODESE DA COLUNA', 'DOR LOMBAR BAIXA', 62, 1.73000001907349, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(64, 60, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(65, 218, 'ASSESORA JURIDACA', 'MICHELLY DALPIAZ', 'SIM', 'PILATES', NULL, NULL, NULL, NULL, NULL, 'DESCONFORTO TORACICA E PESCOCO E CERVICAL', 'EVENTUALMENTE QUANDO ESTA TENCIONADO SENTE EM POSICOES VARIADAS', 'ATIVIDADE FISICA E FORTALECIMENTO MUSCULAR', 'FRAQUEZA', 56, 1.66999995708466, NULL, 'RAZOAVEL', 'FRAQUEZA MUSCULAR GERAL', NULL, 'CREPITACAO AO ESTENDER MAIS NO JOELHO ESQUERDO E COM MENOS INTENSIDADE NO DIREITO', NULL, 'LEVE ESCOLIOSE PARA A DIRETA EM TORACICA', NULL, NULL, NULL),

(66, 219, 'ESTUDANTE', 'ROSIELE ATLETISMO', 'SIM', 'ATLETISMO (PARADO A 2 MESES)', NULL, NULL, NULL, NULL, NULL, 'LOMBAR BAIXA LADO DIREITO', 'DOI AO CORRER RAPIDO (TIRO) COM BASTANTE INTENSIDADE ATE DOER AO ANDAR', 'ALIVIO DA DOR', 'DOR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(67, 220, 'AUX DE RH', 'ROSIELE ACADEMIA', 'SIM', 'MUSCULACAO E CORRIDA', NULL, NULL, NULL, NULL, NULL, 'TORNOZELO ESQUERDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(68, 221, 'DIARISTA', 'ELOIZA', 'SIM', 'PILATES', NULL, NULL, NULL, NULL, NULL, 'DOR LOMBAR QUE IRADIA PARA MMII, INDO PARA VIRILHA, E POSTERIOR DE QUADRIL E COXA
PUNHOS
OMBROS E PESCOCO
PES (HALUX) RAIOX NORMAL', 'CONSTANTE', 'ALIVIO DAS DORES', 'COLUNA IRADIANDO PARA MMII', 63, 1.72000002861023, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(69, 222, 'APOSENTADA', 'MEDICO', 'NÃO', NULL, 'CELOZOKI
CELOZEL
PURAN T4
OSSOS', NULL, NULL, NULL, 'TIREOIDISMO
DIABETES
COLESTEROL ALTERADO', 'COLUNA GERAL', 'AO TRABALHAR EM SERVICOS DOMESTICOS', 'ALIVIO DAS DORES E ATIVIDADE FISICA', 'DOR COLUNA', 57, 1.67999994754791, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(70, 224, 'AUX DE ALMOXARIFADO', 'MATEUS RAPHAELI', 'SIM', 'FUTEBOL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(71, 225, 'TECNICA DE SEGURANCA DE TRABAL', NULL, 'SIM', 'FUTEBOL
MUSCULACAO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(72, 226, 'AUX ADMINISTRATIVO', NULL, 'SIM', 'CORRIDA
ACROYOGA', NULL, NULL, NULL, NULL, NULL, 'BEM NA LATERAL SUPERIOR DO QUADRIL, CRISTAS ILIACAS EM AMBOS OS LADOS', 'AO ANDAR, DEPOIS DE CORRER, DOR LEVE A MODERADA, SENTADA E DEITADA NAO DOI, APENAS SE DEITAR SOBRE O LADO D', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(73, 227, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);