INSERT INTO exames (CODEXAME, CODALUNO, EXAMES, OBSERVACOES)
VALUES
 (1, 1, 'US OMBRO E 07/2010 TENDINOPATIA SUPRA ESPINAL E BURSITE.
ARTRORESSONANCIA OMBRO E 03/2011 TENDINOSE SUPRA ESPINAL, PEQUENA QUANTIDADE DE LÍQUINO NA BURSA.
RM LOMBO SACRA 12/2012 DISCOPATIA EM L4-L5 COM EXTRUSAO DISCAL BASE LARGA MEDIANA A D COMPRIMINDO SACO DURAL E CANAL MEDULAR E FORAME D. ALTERACAO DEGENERATIVA EM L4-L5 E ESPESSAMENTO LIG AMARELO.
RM TORÁCICA 04/2014: T8 - T9 DEGENERACAO E PROTUSAO DISCAL POSTERIOR, LEVE COMPRESSAO SOB SACO DURAL E EM LOMBO SACRA L5-S1 MINIMO ABAULAMENTO DISCAL E ARTROSE.', '2007 SUBMETIDO A RETIRADA DE HD LOMBAR, REAPARECIMENTO EM 2010'),

(2, 2, 'TC TORAX 04/2018: ALTERACAO MORFOLOGICA DA CAIXA TORACICA, DECORRENTE DE IMPORTANTE ESCOLIOSE DOSAL DE CONVEXIDADE A D, ORGAOS EM MORFOLOGIA NORMAL', 'DR JOAO SALUN REALIZOU MEDICAO DE 68 A 75 ° DE ESCOLIOSE
EM JUN/2018 68° DE ESCOLIOSE'),

(3, 3, 'RM LOMBOSACRA 2012: HEMENGIOMAS EM L5 - S1, DISCOPATIA E ABAULAMENTO EM L1-L2, H INTRASSOMATICA SUPERIOR L2, DISCOPATIA EM L5-S1 COM PROTRUSAO DISCAL POSTERIOR A D TOCANDO A RAIZ DE S1. DR CARLOS MORI
RM LOMBO SACRA EM 2018: REDUCAO DA PROTRUSAO DISCAL PARA ABULAMENTO EM L5-S1, DISCOPATIA ACENTUADA NA LOMBAR', 'PASSOU POR VARIOS MEDICOS, POREM NAO INDICAM CIRURGIA PELO COMPROMETIMENTO DE TODA LOMBAR.'),

(4, 4, 'RAIO X 2013: ESCOLIOSE TORACO LOMBAR DE CONVEXIDADE A D 18°. EM MARCO 25°
04/2015 32° MEDICO
04/2015 26° MINHA MEDICAO
10/2015 35°
11/2016 32°', NULL),

(5, 6, 'RAIO X COLUNA LOMBAR NORMAL EM 2018', NULL),

(6, 8, 'RM JOELHO D 03/2013
OSTEOARTROSE MAIS MEDIAL, RUPTURA CORNO POSTERIRO DO MENISCO MEDIAL, CISTO OSSEO NA CABECA DA FIBULA, CISTO DE BAKER, DERRAME ARTICULAR
US OMBRO D: RUPTURA TENDAO E DISTENSAO DA BURSA, CALCIFICACAO DE TENDAO
RAIO X PE D: OSTEOPENIA, REDUCAO DAS ARTICULACOES, OSTEOFITOS E CISTOS, CALCIFICACOES', 'POS CIRURGICO DE OMBRO 12/2012
ALGIA DE JOELHO DESDE 2011
PARKINSON DESDE 2009
DEDOS EM GARRA.
PROTESE JOELHO D EM 2018'),

(7, 9, 'RM 11/2012 LOMBO SACRA: RETIFICACAO DA LORDOSE LOMBAR E NODULO DE SCHOMORL NO PLATO VERTEBRAL SUPERIROR DE L2. HD EXTRUSA CENTRO LATERAL E EM L5-S1 DO LADO E POSTERIOR COMPRIMINDO SACO DURAL.
US COTOVELO D: ESPESSAMENTO E HIPOCONGENUIDADE DO TENDAO COMUM DOS EXTENSORES DOS DEDOS, TENDINOSE. MATERIAL METALICO DA SINFESEFIXA NA DIAFISE DA ULNA (DE ANTIGA FRATURA)

RM 28.08.2019 LOMBO-SACRA DR FABIO SOEJIMA
RETIFICACAO DA LORDOSE LOMBAR E DISCRETA RETROLISTESE DE L5 SOBRE S1
DISCOPATIA DEGENERATIVA AVANCADA EM L5-S1, COM DOENCA DISCOGENICA TIPO I E II DE MODIC NOS PLATOS VERTEBRAIS CORRESONDENTES
ABAULAMENTO DISCAL DIFUSO EM L5-S1, QUE LATERALMENTE SAO ASSOCIADOS A OSTEOFITOS MARGINAIS PROVOCANDO LEVE REDUCAO NA LUZ FORAMIDAL BILATERALMENTE
LEVE ABAULAMENTO DISCAL POSTERIOR EM L1-L2, SEM REPERCUSSAO PARA AS ESTRUTURAS NERVOSAS.', NULL),

(8, 10, NULL, 'ESCOLIOSE DORSAL A D
LIMITACAO DO QUADRIL EM MOV DE ABDUCAO E ROTACAO'),

(9, 12, 'TC LOMBAR 04/2014: ESPONDILO DISCOPATIA DEGENERATIVA INICIAL EM L5-S1 COM ABAULAMENTO DISCAL DIFUSO COM PREDOMINANCIA CENTRAL ENDENTANDO SACO DURAL E INSUNUACAO FORAMIDAL E COM ESTRITAMENTO DO FORAMEN', 'AUMENTO DA HD EM UMA DAS CRISES, AGOAR PROTRUSAO DISCAL EM L5-S1'),

(10, 14, 'RX DE OMBRO D 08/2010: IRREGULARIDADE DO TUBERCULO MAIOR E CONTORNO DO OCROMIO, CALCIFICACOES NO MANGUITO ROTADOR, PARAFUSO NA CABECA UMERAL - INTERVENCAO CIRURGICA DE ROMPIMENTO DE TENDAO
RM JOELHO D 04/2012: DERRAME ARTICULAR, CISTO DE BAKER, DISCRETA LESAO CONDRAL NA PATELA COM REDUCAO DA ESPESSURA E IRREGULARIDADES NA CARTILAGEM - REALIZADO LIMPEZA POR ARTROSCOPIA EM 2013
US TORNOZELO E: EDEMA SUB CALCANEO, PEQUENO DERRAME ARTICULAR, ENTENSOPATIA DE CALCANEO.', '2018: APOS PASSAR EM 2 MÉDICOS TEM INDICACAO DE CIRURGIA DE PROTESE DE JOELHO. UM JOELHO TEM DESGASTE DE MENISCO LATERAL (D) INDO PARA VALGO, E O OUTRO DE MENISCO MEDIAL (E) INDO PARA VARO.'),

(11, 168, 'RM LOMBAR 12.12.2017:
ZIGARTROSE LOMBAR DIFUSA E HIPERTROFIA DO LIGAMENTO AMARELO EM 64-L5
REDUCAO ASSIMETRICA DOS DISCOS INTERVERTEBRAIS DE L2 A L5, COM ALTERACAO DE MOBIC I NOS PLATOS VERTEBRAIS.
ABAULAMENTO DISCAL DIFUSO EM L2-L3 E L3-L4, COM EXTENSAO FORAMIDAL ESQUERDA, TOCANDO A FACE ANTERIOR DO SACO DURAL E RAIZES EMERGENTES
ABAULAMENTO DISCAL DIFUSO EM L4-L5 COM EXTENSAO FORAMIDAL BILATERAL, AMIOR A D, TOCANDO ANTERIORMENTE SACO DURAL, GOSDURA EPIDURAL E FORAMES ANTERIORES E RAIZES EMERGENTES A D.
ABAULAMENTO DISCAL DIFUSO EM L5-S1 TOCANDO A FACE ANTERIOR DO SACO DURAL.
REDUCAO DA AMPLITUDE DOS FORAMES DE CONJUGACAO DE L2 A S1 E DO CANAL VERTEBRAL EM L4-L5.', 'DISCOPATIA DEGENERATIVA E ABULAMENTOS COMPRIMINDO RAIZES NERVOSAS E HIPERTROFIA DO LIGAMENTO AMARELO DE FORMA GENERALIZADA NA COLUNA LOMBAR'),

(12, 170, NULL, 'ARTROPLASTIA COXO FEMORAL E'),

(13, 17, 'RM COLUNA CERVICAL, 11/02/2019:
ABAULAMENTO DISCAL EM C5 - C6 COM LEVE COMPRESSAO DO SACO DURAL A FACE VENTRAL, ESPONDOLOLISE ISTMICA EM C4, A ESQUERDA, NAO HAVENDO ESPONDILOLISTESE.', NULL),

(14, 16, 'RAIO X ESCOLIOSE CONVEXA A E 15 GRAUS', NULL),

(15, 38, 'RM COLUNA LOMBO SACRA. 20.03.2019.
DISCOPATIA DEGENERATIVA DA COLUNA LOMBAR EM L5-S1, HAVENDO PEQUENA PROTRUSAO DISCAL POSTERIOR DE BASE AMPLA E MEDIANA, SEM REPERCURSSAO PARA A LUZ DO CANAL VERTEBRAL E FOMANIDAL.', NULL),

(16, 85, 'TC LOMBO SACRA 22.03.19
ESCOLIOSE LOMBAR CONVEXA A DIREITA, EM DECUBITO. MEGAPOFISE TRASVERSA NEOARTICULADA COM O SACRO A ESQUERDA. DISCOPATIA DEGENERATIVA COM PROLIFERACAO OSTEOFITARIA EM T12 ATE L3. PROTRUSAO DISCAL POSTERIOR MEDIANA EM L4-L5 COMPRIMINDO A FACE ANTERIOR DO SACO DURAL.
DISCOPATIA DEGENERATIVA EM L5-S1 ASSOCIADO A ARTROSE DAS APOFISARIAS', NULL),

(17, 175, 'RAIO X 03/2019
APRESENTOU SOMENTO ESCOLIOSE A CONVEXIDADE A D 14 GRAUS', 'APARENTE MINIMO DIMINUICAO DE ESPACO EM ULTIMAS TORACICAS'),

(18, 15, 'RM QUADRIL 09.04.2019
D. ALTERACOES DEGENERATIVAS OSTEOCONDRAIS NA ARTICULACAO COXOFEMORAL. FORMACAO CISTICA PERIARTICULAR (PROVAVEL CISTO PARALABRAL). SINAIS DE TENDINOPATIA DOS ISQUIOSTIBIAIS E DO GLUTEO MINIMO
E. ALTERACOES DEGENERATIVAS OSTEOCONDRAIS NA ARTICULACAO COXOFEMORAL. SINAIS DE TENDINOPATIA DOS ISQUIOSTIBIAIS E DO GLUTEO MINIMO', NULL),

(19, 177, '30.10.2018 RM QUADRIL D
TENDINOPATIA E PERITENDINITE DOS TENDOES GLUTEOS
02.05.2016 RM COLUNA SACRA
ALTERACOES DEG DA COLUNA LOMBO SACRA
MINIMO ABAULAMENTO DISCAL EM L4-L5
NODULO DE SCHOMOR EM L2.L3
ABAULAMENTO EM L3-L4 COMPRIMENDO A E COM RUPTURA ANULAR', NULL),

(20, 182, '08.11.2016 RM LOMBO SACRA
DESIDRATACAO DISCAL EM L3 L4 COM SINAIS DE DISCOPATIA DEGENARATIVA EM L4 L5 E L5 S1. MODIC TIPO II EM L3 L4
LEVE ABAULAMENTO DO DISCO L3 L4
HERNIA DISCAIS MEDIANA SUBLINGUAR DE BASE AMPLA EL L4 L5 QUE ESTA PROXIMO A RAIZ DE L5 ESQUERDA E REDUZ DE FORMA DISCRETA A AMPLITUDE DO CANAL VERTEBRAL
PROTRUSAO DISCAL MEDIANA DE BASE AMPLA EM L5 S1
SOBRECARGA NOS LUGAMENTOS INTERESPINHOSOS DE L3 L4, L4 L5, L5 S1', NULL),

(21, 146, '04.2019. RM
OSTEITE PUBICA. RUPTURA DO TENDAO ADUTOR LONGO A D JUNTO AO PUBIS. TENDINOPATIA DOS ADUTORES. ESPESAMENTO E ALTERACAO DE SINAL DA APONEOROSE RETOADUTORA', NULL),

(22, 187, 'DENSITOMETRIA OSSEA 20.03.2017
OSTEOPOROSE COLUNA LOMBAR 0,865G/CM2
OSTEOPENIA FEMUR D 0,716 G/CM2

RAIO X 17.09.19 TORACICA E LOMBAR
IRREGULARIDADE NO PLATO VERTEBRAL SUPERIOR DE T 12, COM REDUCAO DE ALTURA DO CORPO VERTEBRAL, POSSIVELMENTE RELACIONADA A FRATURA
REDUCAO DE ESPACO INTERVERTEBRAL ENTRE L5-S1
ARTROSE INTERAPOFISARIAS LOMBAR INFERIOR', NULL),

(23, 186, 'RAIO X TORAX 17.09.2018
ALTERACOES
AUMENTO DO VOLUME CARDIACO
CROCA AORTICA COM PLACAS ATEROMATOSAS
AUMENTO DO DIAMETRO DA AORTA TORACICA
ACENTUACAO CIFOSE E ALTERACOES DEGENERATIVAS DA COLUNA DORSAL', NULL),

(24, 189, 'RM DA BACIA 04/2019
TENDINOPATIA NA ORIGEM DOS ISQUIOTIBIAIS
TENUE EDEMA EM PARTES MOLES ADJACENTES AOS TROCANTERES MAIORES DOS FEMURES BILATERALMENTE.
SEM PREDISPOSICAO A SINDROME DO PIRIFORME E NERVO CIATICO COM TRAJETO E ESPESSURA NORMAIS

RM COLUNA LOMBAR 04/2019
DISCOPATIA DEGENERATIVA INCIPIENTE EM L3-L4 E L4-L5. ABAULAMENTO ASSIMETRICO DO DISCO L4-L5, UM POUCO MAIS EVIDENTE A E E ABAULAMENTO LATERAL ESQUERDO DO DISCO L3-L4, POREM SEM PROVOCAR ESTENOSE FORAMIDAL SIGNIFICATIVA NO EXAME ATUAL. ALTERACOES DEGENERATIVAS INCIPIENTES NAS INTERFACETARIAS LOMBARES INFERIORES COM DISCRETO PROCESSO INFLAMATORIO PERIARTICULAR JUNTO AS INTERFACETARIAS DE L4-L5 A ESQUERDA DE L5-S1 A D
ALTERACAO DEGENERATIVA INFLAMATORIA INCIPIENTE NO LIGAMENTO INTERSPINHOSO DE L4-L5', 'DOR EM AMBOS OS LADOS ABAIXO DOS GLUTEOS E POSTERIOR DE COXA, PORTANTO, MAIS RELACIONADO COM A TENDINOPATIA DE ISQUIOTIBIAIS'),

(25, 98, '24.06.19: UL OMBRO D
TENDAO DA CABECA LONGA DO BICEPS TOPICO, COM ESPESSURA E ACOTEXTURA NORMAIS, APRESENTANDO QUANTIDADE FISIOLOGICA DE LIQUIDO AO SEU REDOR.
BURSA SUBACROMIAL/SUBDOLTOIDEA APRESENTADO DISCRETO ESPESSAMENTO.
ARTICULACAO ACROMIOCLAVICULAR COM DISCRETA IRREGULARIDADE OSSEA E HIPERTROFIA CAPSULOLIGAMENTAR', NULL),

(26, 199, '16.05.2019. RM OMBRO D
TENDINOSE DO SUPRA ESPINHOSO
LEVE BURSITE SUBACROMIODELTOIDEIA
16.05.2019 TC SACRO ILIACAS
DENTRO DOS PADROES DE NORMALIDADE', NULL),

(27, 192, NULL, '2019. REALIZOU CONSULTA COM ORTOPEDISTA E EXAMES DE LOMBAR E ESTA TUDO DENTRO DO NORMAL.
DOR LOMBAR DEVE TER ORIGEM MUSCULAR'),

(28, 30, 'RM LOMBO SACRA 16.08.2019.
DISCRETA RETROLISTESE DE L5 SOBRE S1
DISCOPATIA DEGENERATIVA EM T12-L1 E L5-S1 QUE FAZ IMPRESSAO SOBRE O SACO DURAL.
PROTRUSAO DISCAL CENTROLATERAL D EM Y12-L1 COM HD CENTRO LATERAL ESQUERDA, QUE FAZ IMPRESSAO SOBRE O SACO DURAL E ESTABELECE CONTATO COM A ORIGEM DA RAIZ NERVOSA DE S1 ESUQERDA
SINAIS DE LESAO POR SOBRECARGA NOS LIGAMENTOS INTERESPINHOSOS LOMBARES A ECXESAO DE L1-L2', NULL),

(29, 203, '03.06.2019. EIXO LOMBAR PARA ESQUERDA', 'CURVAS LORDOTICAS E CIFOTICAS ACENTUADAS- CORRESPONDENDO A MÁ POSTURA'),

(30, 208, 'RM COLUNA LOMBAR 22.03.2019 FABIO SOEJIMA
RETIFICACAO DA LORDOSE
DISCOPATIA DEGENERATIVA TORACICA INFERIROR E LOMBAR DIFUSA COM EXCECAO DE L4-L5 L5-S1
PROTRUSAO DISCAL MEDIANA EM L2-L3 QUE FAZ IMPRESSAO SOBRE O SACO DURAL
DISCRETO ABAULAMENTO DISCAL DIFUSO EM L3-L4 COM SINAIS DE FISSURA ANULAR RADIAL POSTERIOR
SINAIS DE LESAO POR SOBRECARGA NOS LIGAMENTOS INTERESPINHOSOS LOMBARES, A EXCECAO DE L1-L2
NODULO DE SCHMORL NOS PLATOS VERTEBRAIS TORACICOS INFERIORES E L1, L2, L3 E L4
ASSIMETRIA DAS INTERFACETARIAS  EM L4-L5 COM ASPETO HIPOPLASTICO A E

RM COLUNA CERVICAL  22.03.2019 FABIO SOEJIMA
RETIFICACAO DA LORDOSE CERVICAL
DISCOPATIA DEGENERATIVA EM C5-C6, COM PROTRUSAO DISCAL DE BASE AMPLA CENTRO LATERAL E FORAMIDAL ESQUERDA, QUE OBLITERA PARCIALMENTE O ESPACO EPIDURAL ANTERO LATERAL A ESQUERDA NESTE NIVEL, EM POSSIVEL TRAJETO DA RAIZ NERVOSA DE C6 ESQUERDA, E ASSOCIADO A UNCOARTROSE REDUZ A AMPLITUDE DO FORAME DE CONJUGACAO CORRESPONDENTE.', 'DEGENERACAO TOTAL EM LOMBAR, SINTOMA DE IRADIACAO PARA MID

HERNIA DE DISCO IMPORTANTE NA CERVICAL COMPRIMINDO CANAL MEDULAR E RAIZ NERVOSA A ESQUERDA
SINTOMA DE IRADIACAO PARA E

AMBAS CURVATURAS RETIFICADAS'),

(31, 90, 'RADIOGRAFIA DE OMBRO D E E
AMBOS:
CONTROLE DE TRATAMENTO ORTOPEDICO
OSTEOPENIA
PARAFUSO DE ANCORAGEM NO UMERO PROXIMAL
REDUCAO DO ESPACO ACROMIOCLAVICULAR, ASSOCIADA A CISTOS SUBCONDRAIS
PARTES MOLES SEM ALTERACOES
ACROMIO TIPO II', NULL),

(32, 61, 'RM COLUNA LOMBO SACRA
DISCOPATIA DEGENERATIVA EM L5-S1 COM REDUCAO DE ALTURA E OSTEOFITOS MARGINAIS INCIPIENTES
DISCOS L2-L3, L3-L4, L4-L5 APRESENTAM LEVE SINAL DE DESIDRATACAO, COM OSTEOFITOS SOMATICOS ANTERO LATERAIS
PROTRUSAO DISCAL EM L2-L3 FORAMIDAL E EXTRAFORAMIDAL ESQUERDA, REDUZINDO FORAME NEURAL DESTE LADO.
PEQUENOS ABAULAMENTOS LEVEMENTE ASSIMETRICOS EM L3-L4 E L4-L5, OBLITERANDO O ASPECTO INFERIOR DOS FORAMES NEURAIS A D, ASSOCIASE FISSURA ANULAR EM L4-L5
EM L5-S1 HA PEQUENA PROTRUSAO DISCAL PARAMEDIANA ESUQERDA, COM FISSURA ANULAR OBLITERANDO A GORDURA EPIDURAL ANTERIOR TOCANDO A RAIZ  DE S1
ALTERACOES DEGENARATIVAS INCIPIENTES NAS ARTICULACOES INTERAPOFISARIAS COM LEVE ESPESSAMENTO DOS LIG AMARELOS DE L1 A L4', NULL),

(33, 217, '20.09.2019 RM COLUNA LOMBAR
ESPONDILOLISE BILATERAL EM L5 COM ESPONDILOLISTESE GRAU I/II SOBRE S1
ESPONDILODISCOPATIA DEGENERATIVA EM L5-S1
NIVEL L5-S1: PSEUDOPROTRUSAO DISCAL DIFUSA COM EXTENSAO AOS SEGMENTOS FORAMINAIS, ESTANDO OS MESMOS DEFORMADOS E COM AMPLITUDE REDUZIDA
ALTERACOES DEGENERATIVAS DISCOGENICAS DO TIPO I NOS PLATOS DE L5-S1, HAVENDO REMODELAMENTO OSSEO NA MARGEM ANTERIOR DE S1 POR VOLUMOSO NODULO DE SCHMORL', NULL),

(34, 221, 'RM LOMBO SACRA 01.04.2019
ALTERACOES DEGENERATIVAS HIPERTROFICAS NAS ARTICULACOES INTERAPOFISARIAS DE L4-L5 E DE L5-S1. AUSENCIA DE HERNIAS DISCAIS
NODULO DE SCHMORL EM L1-L2
SEM OSTEOFITOS', 'DOR LOMBAR IRADIADA PARA AMBOS MMII'),

(35, 222, 'DEGENERACAO DE COLUNA LOMBAR E ESPONDILOLISTESE
CERVICAL ABAULAMENTO E UNCOARTROSE', NULL);


